<a href="https://colab.research.google.com/github/NohaWaly/Neural-Network-keras/blob/master/Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
! git clone https://github.com/ardamavi/Sign-Language-Digits-Dataset.git

fatal: destination path 'Sign-Language-Digits-Dataset' already exists and is not an empty directory.


In [0]:
import numpy as np
import matplotlib.pyplot as plt
#cv2 to read image, show and more
import cv2
import os
import random
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from keras.utils import to_categorical

DataDir = "Sign-Language-Digits-Dataset/Dataset"
ImgSize = 100

Categories = ["0", "1","2","3", "4","5","6", "7","8","9"]
data = []
#iterate over 10 folders
for category in Categories:  
    # create path to each gesture 
    path = os.path.join(DataDir,category) 
    classNum = Categories.index(category)
    #print(path)
    # iterate over each image per each gesture 
    for img in os.listdir(path): 
        #print(img)
        # convert to array
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_GRAYSCALE) 
        # resize & divide with 255 to normalize data
        resize_array = cv2.resize(img_array, (ImgSize, ImgSize))/255
        #append to data
        data.append([resize_array, classNum])
    
    

     


In [0]:
       
#shuffle data (msh kol class ykon wara b3d)
random.shuffle(data)  
#print(data)


In [14]:
X = []
y = []

for features, label in data:
   X.append(features)
   y.append(label)
#to enter the model it should be np array
X = np.array(X)
y = np.array(y,dtype=int)

#hot incoder
#y = to_categorical(y)

print(X)
print(y)



[[[0.48235294 0.49411765 0.50196078 ... 0.45882353 0.45490196 0.45098039]
  [0.48627451 0.50196078 0.50588235 ... 0.46666667 0.45882353 0.45490196]
  [0.49411765 0.50588235 0.51372549 ... 0.4745098  0.47058824 0.4627451 ]
  ...
  [0.48627451 0.49411765 0.50588235 ... 0.51764706 0.50980392 0.50196078]
  [0.47058824 0.48235294 0.49411765 ... 0.50980392 0.50196078 0.49411765]
  [0.47058824 0.4745098  0.48235294 ... 0.50588235 0.49411765 0.49019608]]

 [[0.46666667 0.4745098  0.47843137 ... 0.42352941 0.41568627 0.40784314]
  [0.46666667 0.4745098  0.48235294 ... 0.42745098 0.41960784 0.41176471]
  [0.46666667 0.47843137 0.49019608 ... 0.42352941 0.41568627 0.41176471]
  ...
  [0.36078431 0.36470588 0.37254902 ... 0.35294118 0.34901961 0.34509804]
  [0.35686275 0.36078431 0.36862745 ... 0.34901961 0.34117647 0.3372549 ]
  [0.35294118 0.36078431 0.36470588 ... 0.34509804 0.3372549  0.33333333]]

 [[0.51764706 0.52156863 0.52941176 ... 0.43921569 0.43529412 0.43137255]
  [0.51764706 0.521568

In [0]:
#spliting training & test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=7)

In [0]:
def create_neural_network1():
    #making the model
  model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
  model.compile(optimizer = tf.train.AdamOptimizer(),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
  return model


In [0]:
def create_neural_network2():
    #making the model
  model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
  model.compile(optimizer = tf.train.AdamOptimizer(),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
  return model

In [0]:
def create_neural_network3():
    #making the model
  model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                      tf.keras.layers.Dense(360, activation=tf.nn.relu), 
                                      tf.keras.layers.Dense(360, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
  model.compile(optimizer = tf.train.AdamOptimizer(),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
  return model

In [0]:
def create_neural_network4():
    #making the model
  model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                      tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
  model.compile(optimizer = tf.train.AdamOptimizer(),loss = 'sparse_categorical_crossentropy',metrics=['accuracy'])
  return model

In [20]:
n_split = 4
val_loss = np.zeros(n_split)
val_acc = np.zeros(n_split)

k_Fold = KFold(n_splits=4)
models = [create_neural_network1,create_neural_network2,create_neural_network3,create_neural_network4]
for x in range(4):
  i=0
  for train, validate in k_Fold.split(X_train, y_train):
      model = models[x]()
      model.fit(X_train[train], y_train[train], epochs=50)
      val_loss[i], val_acc[i] = model.evaluate(X_train[validate],y_train[validate])
      i+=1
  print("Average Loss and Accuracy in Architecture" +str(x+1))
  print(val_loss.mean())
  print(val_acc.mean()) 
  #evaluate the testing part
  print("Evaluate testing part")
  model.evaluate(X_test, y_test)
  #get predicted labels
  y_predict = model.predict_classes(X_test)
  #evaluate model using precision, fscore, & recall
  print(classification_report(y_test, y_predict, target_names=Categories))
  

Train on 1236 samples
Epoch 1/50
1236/1236 [==============================] - 0s 333us/sample - loss: 2.7547 - acc: 0.1052
Epoch 2/50
1236/1236 [==============================] - 0s 243us/sample - loss: 2.3295 - acc: 0.1489
Epoch 3/50
1236/1236 [==============================] - 0s 243us/sample - loss: 2.1916 - acc: 0.1780
Epoch 4/50
1236/1236 [==============================] - 0s 241us/sample - loss: 2.0266 - acc: 0.2638
Epoch 5/50
1236/1236 [==============================] - 0s 240us/sample - loss: 1.9465 - acc: 0.3066
Epoch 6/50
1236/1236 [==============================] - 0s 243us/sample - loss: 1.7292 - acc: 0.3989
Epoch 7/50
1236/1236 [==============================] - 0s 246us/sample - loss: 1.5244 - acc: 0.4547
Epoch 8/50
1236/1236 [==============================] - 0s 241us/sample - loss: 1.4023 - acc: 0.5008
Epoch 9/50
1236/1236 [==============================] - 0s 257us/sample - loss: 1.3515 - acc: 0.5267
Epoch 10/50
1236/1236 [==============================] - 0s 250us/sam